language: java
jdk: oraclejdk8

before_install: chmod +x gradlew
install: "./gradlew setupCIWorkspace"
script: "./gradlew build"

deploy:
  provider: releases
  api_key: '$API_KEY'
  file_glob: true
  file: 'build/libs/*.jar'
  skip_cleanup: true
  on:
    tags: true
    branch: master